postgres:
  dsn: "postgresql://postgres:postgres@127.0.0.1:5432/test?sslmode=disable" # e.g. "postgres://localhost:5431"
parquet:
  file:
    path: "test2.parquet" #"2023-01-01.parquet"
milvus:
  server: "localhost:19530"
limits:
  batch_size: 10
  max_records: 30000
date: # format: "yyyy-mm-dd"
  start: "2023-01-01"
  end: "2023-02-01"
  window_days: 80 # also the dimension of Milvius vector